apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: scheduled-volume-operation
spec:
  schedule: "0 1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: scheduled-operation
            image: busybox
            command: ["/bin/sh", "-c", "echo 'Scheduled operation' >> /data/scheduled-ops.log"]
            volumeMounts:
            - name: data-volume
              mountPath: /data
          restartPolicy: OnFailure
          volumes:
          - name: data-volume
            persistentVolumeClaim:
              claimName: backend-pvc
